-- Active: 1730574430233@@127.0.0.1@5432@postgres

CREATE USER "web_user" WITH PASSWORD '0707';
GRANT ALL PRIVILEGES ON DATABASE SMART_WARDROBE TO  "web_user" ;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "web_user" ;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "web_user" ;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "web_user" ;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "web_user" ;
GRANT ALL PRIVILEGES ON SCHEMA public TO "web_user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "web_user";


GRANT ALL PRIVILEGES ON DATABASE "SMART_WARDROBE" TO "web_user" ;
GRANT USAGE, CREATE ON SCHEMA public TO "web_user";




 "SMART_WARDROBE";

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'F'))
);


SELECT *FROM users_user;