# Generated by Django 5.1.7 on 2025-04-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('upper', 'Upper Clothing'), ('lower', 'Lower Clothing'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], max_length=20)),
                ('original_image', models.ImageField(upload_to='clothes/original/')),
                ('segmented_image', models.ImageField(blank=True, null=True, upload_to='clothes/segmented/')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
