# Generated by Django 5.1.7 on 2025-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='original_image',
            field=models.ImageField(upload_to='original_clothes/'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='segmented_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_clothes/'),
        ),
    ]
